services:
  
  
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped


volumes:
  mssql_data:
